begin;
do $test$
declare sid bigint; st bigint; other_st bigint; cid bigint; actor uuid; x jsonb; y jsonb; b jsonb; failed boolean; d date:=(now() at time zone 'Asia/Tokyo')::date+10;
begin
 select m.store_id,m.user_id,br.company_id into st,actor,cid from public.store_memberships m join public.stores s on s.id=m.store_id join public.brands br on br.id=s.brand_id where m.active and m.role in ('manager','owner','admin') limit 1;
 select s.id into other_st from public.stores s join public.brands br on br.id=s.brand_id where br.company_id=cid and s.id<>st limit 1;
 insert into public.staff_roster(company_id,display_name,hourly_wage) values(cid,'__guarded_shift_test__',1100) returning id into sid;
 insert into public.staff_store_assignments(staff_id,store_id) values(sid,st),(sid,other_st);
 b:=jsonb_build_object('action','shift_create','staff_id',sid,'store_id',st,'shift_date',d,'scheduled_start','11:00','scheduled_end','15:00');
 x:=public.manage_roster_shift(actor,b);
 if x->>'status'<>'scheduled' then raise exception 'create failed'; end if;
 failed:=false;begin perform public.manage_roster_shift(actor,b||jsonb_build_object('store_id',other_st));exception when others then failed:=true;end;
 if not failed then raise exception 'cross-store overlap allowed';end if;
 b:=b||jsonb_build_object('action','shift_update','shift_id',x->'id','expected_updated_at',x->'updated_at','scheduled_end','16:00');
 y:=public.manage_roster_shift(actor,b);
 if y->>'scheduled_end'<>'16:00:00' then raise exception 'update failed';end if;
 failed:=false;begin perform public.manage_roster_shift(actor,b);exception when others then failed:=true;end;
 if not failed then raise exception 'stale update allowed';end if;
 b:=jsonb_build_object('action','attendance_save','shift_id',y->'id','expected_updated_at',y->'updated_at','clock_in',d::text||'T11:00:00+09:00','clock_out',d::text||'T16:00:00+09:00','break_minutes',30,'reason','打刻忘れ');
 failed:=false;begin perform public.manage_roster_shift(actor,b||'{"break_minutes":301}'::jsonb);exception when others then failed:=true;end;
 if not failed then raise exception 'excess break allowed';end if;
 failed:=false;begin perform public.manage_roster_shift(actor,b||'{"break_minutes":-1}'::jsonb);exception when others then failed:=true;end;
 if not failed then raise exception 'negative break allowed';end if;
 failed:=false;begin perform public.manage_roster_shift(actor,b||'{"reason":""}'::jsonb);exception when others then failed:=true;end;
 if not failed then raise exception 'missing reason allowed';end if;
 x:=public.manage_roster_shift(actor,b);
 if (x->>'labor_cost')::int<>4950 then raise exception 'labor calculation failed';end if;
 failed:=false;begin perform public.manage_roster_shift(actor,jsonb_build_object('action','shift_cancel','shift_id',x->'id','expected_updated_at',x->'updated_at','reason','取消テスト'));exception when others then failed:=true;end;
 if not failed then raise exception 'completed shift cancelled';end if;
 x:=public.manage_roster_shift(actor,jsonb_build_object('action','shift_create','staff_id',sid,'store_id',st,'shift_date',d+1,'scheduled_start','11:00','scheduled_end','15:00'));
 failed:=false;begin perform public.manage_roster_shift('00000000-0000-0000-0000-000000000000',jsonb_build_object('action','shift_cancel','shift_id',x->'id','expected_updated_at',x->'updated_at','reason','権限テスト'));exception when others then failed:=true;end;
 if not failed then raise exception 'unauthorized cancel allowed';end if;
 y:=public.manage_roster_shift(actor,jsonb_build_object('action','shift_cancel','shift_id',x->'id','expected_updated_at',x->'updated_at','reason','予定変更'));
 if y->>'status'<>'cancelled' then raise exception 'cancel failed';end if;
 if not exists(select 1 from public.audit_logs where entity_type='work_shift' and entity_id=y->>'id' and action='shift_cancel' and details->>'reason'='予定変更') then raise exception 'audit missing';end if;
 if has_function_privilege('anon','public.manage_roster_shift(uuid,jsonb)','EXECUTE') or has_function_privilege('authenticated','public.manage_roster_shift(uuid,jsonb)','EXECUTE') then raise exception 'RPC exposed';end if;
end;$test$;
select 'PASS: create, update, cross-store overlap, stale update, attendance validation and calculation, cancellation, audit, access controls' as result;
rollback;
