insert into public.stores (brand_id,name,timezone)
select s.brand_id,'白木原店','Asia/Tokyo' from public.stores s
where s.id=1 and not exists (select 1 from public.stores where name='白木原店');

create table if not exists public.staff_roster (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id),
  display_name text not null check (length(trim(display_name)) between 1 and 80),
  employment_type text not null default 'part_time' check (employment_type in ('part_time','fixed_salary')),
  hourly_wage integer not null default 0 check (hourly_wage >= 0),
  monthly_salary integer not null default 0 check (monthly_salary >= 0),
  nationality text,
  note text,
  auth_user_id uuid unique references auth.users(id) on delete set null,
  active boolean not null default true,
  joined_on date,
  left_on date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(company_id,display_name)
);
create table if not exists public.staff_store_assignments (
  id bigint generated by default as identity primary key,
  staff_id bigint not null references public.staff_roster(id) on delete cascade,
  store_id bigint not null references public.stores(id),
  role text not null default 'staff' check (role in ('staff','manager','owner')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(staff_id,store_id)
);
create index if not exists staff_roster_company_active_idx on public.staff_roster(company_id,active);
create index if not exists staff_store_assignments_store_active_idx on public.staff_store_assignments(store_id,active);
alter table public.staff_roster enable row level security;
alter table public.staff_store_assignments enable row level security;
revoke all on public.staff_roster from anon,authenticated;
revoke all on public.staff_store_assignments from anon,authenticated;
grant all on public.staff_roster to service_role;
grant all on public.staff_store_assignments to service_role;
grant usage,select on sequence public.staff_roster_id_seq to service_role;
grant usage,select on sequence public.staff_store_assignments_id_seq to service_role;

-- Actual employee records are intentionally not committed to source control.
-- They are entered through the authenticated staff-management screen.
